# Generated by Django 4.2.7 on 2023-12-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='sender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
