# Generated by Django 4.2.7 on 2023-12-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_password_patient_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='surname',
        ),
    ]
