# Generated by Django 4.2.7 on 2023-12-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hospitalbranch_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbranch',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
